### PR TITLE
Switched to blending-only for constrained trajectories

### PR DESCRIPTION
**Pull request by mkoval**
This pull request disables short-cutting for constrained trajectories. I enabled blending with some heuristic parameters that seem to produce relatively smooth trajectories that follow the constraint.

This is a temporary workaround because we don't have a proper constrained smoothing.

### CODE REVIEW

**Comment by mkoval** [comment]
@jeking04 Thoughts on this? If you don't mind, could you try running the demo with these changes and see if you notice any difference?

**Comment by mkoval** [comment]
@jeking04 Could you give this a shot and see how the trajectories look?

**Comment by jeking04** [comment]
@mkoval, I ran several runs of the demo yesterday on HERB with this branch and everything looked good.

**Comment by mkoval** [comment]
If it's good enough for @jeking04, it's good enough for me. Merging!

**Pull request merged**
