### PR TITLE
add init_node back to enable talker. fixes #59

### LINKED ISSUE #59: Talker broken because rospy node init removed
9e5d4a353d9533806b99ccc8a7378f838d59c4ee commented out the `init_node` necessary for the `Say()` action to work.

### PR DESCRIPTION
**Pull request by ClintLiddick**

### CODE REVIEW

**Comment by jeking04** [comment]
We originally removed this line because we were having trouble in block sorting when we had already initialized a node. This line was causing a crash on initialization of the robot. However, I tried a simple test to recreate this error and was unable to. Specifically, I added the call ```rospy.init_node('herbpy', anonymous=True)``` into the herbpy ```console.py``` script before calling ```herbpy.initialiaze``` and everything ran okay. Still, I'd like to run block sorting on the robot one time with this fix before merging, just to be sure. I'll do that shortly and post an update.

**Comment by mkoval** [comment]
@jeking04 Let me know when you've had a chance to test this so I can merge it.

**Comment by ClintLiddick** [comment]
@jeking04 let's make sure we test this when we prep for the demo with @romesc-CMU

**Comment by mkoval** [comment]
@ClintLiddick Did you verify that this worked in the demo last week?

**Comment by ClintLiddick** [comment]
It worked, but I never saw it breaking anything, so I'm not comfortable giving it the OK. I'd like someone who saw it not working to check it out.

**Comment by jeking04** [comment]
I saw it work too. Lets merge.

On Tue, Dec 1, 2015 at 8:46 AM, Clint Liddick <notifications@github.com>
wrote:

> It worked, but I never saw it breaking anything, so I'm not comfortable
> giving it the OK. I'd like someone who saw it not working to check it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/personalrobotics/herbpy/pull/60#issuecomment-160974401>
> .
>



-- 
Jen King

**Pull request merged**
