### PR TITLE
Adding lift and place actions

### PR DESCRIPTION
**Pull request by jeking04**
This adds a lift and place action to the action library.  This enables a simple demo from the herbpy console:

```
robot.DetectObjects()
cup = ...
robot.PushGrasp(cup)
robot.Lift(cup)
table = ...
robot.Place(cup, table)
```

### CODE REVIEW

**Comment by mkoval** [comment]
I just noticed that I never merged this. :sweat: 

@jeking04 @rachelholladay is this still something that we should merge into `master`?

If so, please:
- fix the merge conflicts
- fix permissions; it looks like a bunch of files were accidentally marked as executable
- what is the `config/natural_feature_weights.pickle` file? can we remove this?

**Comment by rachelholladay** [comment]
@mkoval This branch inadvertently contains rogue stuff which has its own branch (feature/rogue) which is not quite ready to be merged in. I'll be putting in the pull request for that probably shortly after I return. 
I'm betting @jeking and/or I started this branch from the rogue branch which is how this got mixed up. Since rogue isn't ready I'll remove it from this branch and do the suggested clean up. I'll commit as soon as I'm not waiting in airports. Coolio? Rad.

**Comment by mkoval** [comment]
Airports have wifi, don't they?

(Just kidding.)

**Comment by mkoval** [comment]
This is replaced by #37.

**Pull request closed without merging**
